library:
  source-dirs: src
tests:
  brackets-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brackets
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- text
- base >= 4.7 && < 5
name: brackets
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/brackets
license: BSD3
executables:
  brackets-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deepseq
    - directory
    - random-shuffle
    - unicode-show
    - brackets
description: Please see the README on GitHub at <https://github.com/githubuser/brackets#readme>
